# Generated by Django 2.2.5 on 2019-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0002_auto_20190917_1326")]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_top_up",
            field=models.BooleanField(default=False),
        )
    ]
