# Generated by Django 2.2.5 on 2019-09-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("billing", "0003_transaction_is_top_up")]

    operations = [
        migrations.AlterModelOptions(
            name="exchangerate", options={"ordering": ("-date",)}
        )
    ]
